services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: momo-store-backend:local
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: momo-store-frontend:local
    depends_on:
      - backend
    ports:
      - "80:8080"
